language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

jobs:
  include:
    - stage: "Test-Backend"
      script: docker-compose run backend sh -c "python manage.py test"

    - stage: "Test-Frontend"
      script: docker-compose run frontend sh -c "CI=true yarn test"