language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

jobs:
  include:
    - stage: "Test-Backend"
      script: docker-compose -f docker-compose.yml -f docker-compose.test.yml run backend

    - stage: "Test-Frontend"
      script: docker-compose -f docker-compose-yml -f docker-compose.testyml run frontend