version: "3.5"

services:
  backend:
    volumes: 
      - ./backend/app:/app
    command: >
      sh -c "python manage.py test"

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment: 
      -  REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
    command: sh -c "CI=true yarn test"
