version: "3.5"

services:
  backend:
    build: 
      context: .
    ports: 
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

