version: "3.5"

services:
  backend:
    build: 
      context: ./backend
    ports: 
      - "8000:8000"
    environment: 
       # set this environment variable to the url of the frontend to enable cors for this url
       - FRONTEND_URL=http://localhost
       # set the allowed hosts for django
       - DJANGO_ALLOWED_HOSTS=localhost

  frontend:
    build:
      context: ./frontend
      args:
        # sets the url of the backend
        - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "80:80"
