version: "3.5"

services:
  backend:
    volumes: 
      - ./backend/app:/app
    environment:
      # sets django debug mode to true 
      - DJANGO_DEBUG=True
    command: "test"

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment: 
      # sets the url of the backend
      -  REACT_APP_API_URL=http://localhost:8000
    command: sh -c "CI=true yarn test"
